comment:
  image:
    repository: xxdeenxx/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: xxdeenxx/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: xxdeenxx/ui
    tag: latest
  service:
    externalPort: 9292
