version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${VERVION_UI}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${VERVION_POST}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${VERVION_COMMENT}
    networks:
      - back_net
      - front_net

volumes:
  post_db:
networks:
  back_net:
  front_net:
