version: '3.3'
services:
  ui:
    volumes:
      - ui:/app
    command: puma --debug -w 2
  post:
    volumes:
      - post-py:/app
  comment:
    volumes:
      - comment:/app
volumes:
  ui:
  post-py:
  comment:
